development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: Gtar
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: Gtar
  password: 